---
name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Pulumi Preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["20"]
        stack:
          - dev
          - ws2024

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          exportToken: true
          outputToken: true
          secrets: |
            github-fh-burgenland-bswe-assignment-infrastructure/data/aws region | AWS_REGION ;
            github-fh-burgenland-bswe-assignment-infrastructure/data/aws identity_role_arn | AWS_IDENTITY_ROLE_ARN ;
            github-fh-burgenland-bswe-assignment-infrastructure/data/github token | GH_PAT_TOKEN

      - uses: pulumi/auth-actions@80dec0d5e009a11565cbf87d9ef9103fc7d24198 # v1.0.0
        with:
          organization: dmuehlbachler-fh-burgenland
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:dmuehlbachler-fh-burgenland

      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.AWS_IDENTITY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          yarn install --immutable
          yarn build

      - uses: pulumi/actions@c7fad9e2f0b79653172b36538b8b34b3c0291952 # v6.0.0
        with:
          command: preview
          stack-name: ${{ matrix.stack }}
          refresh: true
        env:
          GITHUB_TOKEN: "${{ env.GH_PAT_TOKEN }}"
          VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"

  deploy:
    runs-on: ubuntu-latest
    name: Pulumi Deploy
    needs:
      - preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["20"]
        stack:
          - dev
          - ws2024

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          exportToken: true
          outputToken: true
          secrets: |
            github-fh-burgenland-bswe-assignment-infrastructure/data/aws region | AWS_REGION ;
            github-fh-burgenland-bswe-assignment-infrastructure/data/aws identity_role_arn | AWS_IDENTITY_ROLE_ARN ;
            github-fh-burgenland-bswe-assignment-infrastructure/data/github token | GH_PAT_TOKEN

      - uses: pulumi/auth-actions@80dec0d5e009a11565cbf87d9ef9103fc7d24198 # v1.0.0
        with:
          organization: dmuehlbachler-fh-burgenland
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:dmuehlbachler-fh-burgenland

      - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ env.AWS_IDENTITY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          yarn install --immutable
          yarn build

      - uses: pulumi/actions@c7fad9e2f0b79653172b36538b8b34b3c0291952 # v6.0.0
        with:
          command: up
          stack-name: ${{ matrix.stack }}
        env:
          GITHUB_TOKEN: "${{ env.GH_PAT_TOKEN }}"
          VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"
