---
name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Pulumi Preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["20"]
        stack:
          - dev
          - ws2024

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: hashicorp/vault-action@v3
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          exportToken: true
          outputToken: true
          secrets: |
            github-fh-burgenland-bswe-assignment-infrastructure/data/aws region | AWS_REGION ;
            github-fh-burgenland-bswe-assignment-infrastructure/data/aws identity_role_arn | AWS_IDENTITY_ROLE_ARN ;
            github-fh-burgenland-bswe-assignment-infrastructure/data/github token | GH_PAT_TOKEN

      - uses: pulumi/auth-actions@v1
        with:
          organization: dmuehlbachler-fh-burgenland
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:dmuehlbachler-fh-burgenland

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_IDENTITY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          yarn install --immutable
          yarn build

      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: ${{ matrix.stack }}
          refresh: true
        env:
          GITHUB_TOKEN: "${{ env.GH_PAT_TOKEN }}"
          VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"

  deploy:
    runs-on: ubuntu-latest
    name: Pulumi Deploy
    needs:
      - preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["20"]
        stack:
          - dev
          - ws2024

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: hashicorp/vault-action@v3
        id: import-secrets
        with:
          method: jwt
          url: ${{ secrets.VAULT_ADDR }}
          path: ${{ secrets.VAULT_PATH }}
          role: ${{ secrets.VAULT_ROLE }}
          exportToken: true
          outputToken: true
          secrets: |
            github-fh-burgenland-bswe-assignment-infrastructure/data/aws region | AWS_REGION ;
            github-fh-burgenland-bswe-assignment-infrastructure/data/aws identity_role_arn | AWS_IDENTITY_ROLE_ARN ;
            github-fh-burgenland-bswe-assignment-infrastructure/data/github token | GH_PAT_TOKEN

      - uses: pulumi/auth-actions@v1
        with:
          organization: dmuehlbachler-fh-burgenland
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:dmuehlbachler-fh-burgenland

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_IDENTITY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          yarn install --immutable
          yarn build

      - uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ${{ matrix.stack }}
        env:
          GITHUB_TOKEN: "${{ env.GH_PAT_TOKEN }}"
          VAULT_ADDR: "${{ secrets.VAULT_ADDR }}"
